# Generated by Django 4.2.4 on 2024-03-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0002_alter_workoutplan_exercise_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='exercise_types',
            field=models.ManyToManyField(related_name='workout_plans', to='workout_plan.exercise'),
        ),
    ]
